# Generated by Django 3.2.5 on 2022-01-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetails',
            name='account_number',
            field=models.CharField(default='000000000000', max_length=250),
        ),
    ]
