# Generated by Django 3.2.5 on 2021-08-03 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(blank=True, max_length=191, null=True)),
                ('certification', models.CharField(blank=True, max_length=191, null=True)),
                ('total_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('competency_area', models.CharField(blank=True, max_length=191, null=True)),
                ('awards', models.CharField(blank=True, max_length=191, null=True)),
                ('would_like_to_teach', models.CharField(blank=True, max_length=191, null=True)),
                ('fac_resume', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('id_proof_image', models.FileField(blank=True, null=True, upload_to='image/')),
                ('fac_type', models.CharField(blank=True, choices=[('guest', 'guest'), ('member', 'member')], max_length=199, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teachers',
                'verbose_name_plural': 'Teacher',
                'db_table': 'teachers',
            },
        ),
    ]
