# Generated by Django 3.2.5 on 2021-08-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_teacher_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='step',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
