# Generated by Django 3.2.5 on 2021-09-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='year_of_experience',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
