# Generated by Django 3.2.5 on 2021-09-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_alter_course_year_of_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='dates_times',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='year_of_experience',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
