# Generated by Django 3.2.5 on 2021-12-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0017_test_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher_category',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
