# Generated by Django 3.2.5 on 2021-10-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomMeetingCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_url', models.CharField(default='', max_length=199)),
                ('meeting_password', models.CharField(blank=True, max_length=199, null=True)),
                ('meeting_topic', models.CharField(blank=True, max_length=199, null=True)),
                ('meeting_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'zoommeetingcreate',
            },
        ),
    ]
