# Generated by Django 3.2.5 on 2021-08-03 12:47

from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_number', models.CharField(blank=True, max_length=191, null=True)),
                ('street_name', models.CharField(blank=True, max_length=191, null=True)),
                ('sub_premise', models.CharField(blank=True, max_length=191, null=True)),
                ('city', models.CharField(blank=True, db_index=True, max_length=191, null=True)),
                ('state', models.CharField(blank=True, max_length=191, null=True)),
                ('country', models.CharField(blank=True, max_length=191, null=True)),
                ('phonecode', models.IntegerField(blank=True, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=191, null=True)),
                ('state_code', models.CharField(blank=True, max_length=191, null=True)),
                ('country_code', models.CharField(blank=True, max_length=191, null=True)),
                ('timezone', timezone_field.fields.TimeZoneField(default='Asia/Kolkata')),
                ('latitude', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
                ('google_place_id', models.CharField(blank=True, max_length=191, null=True)),
                ('google_processed', models.BooleanField(default=False)),
                ('preferred', models.BooleanField(default=False)),
                ('user_created', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=225, unique=True, verbose_name='email')),
                ('secondary_email', models.EmailField(blank=True, max_length=225, null=True)),
                ('username', models.CharField(max_length=191)),
                ('first_name', models.CharField(blank=True, max_length=191, null=True)),
                ('last_name', models.CharField(blank=True, max_length=191, null=True)),
                ('full_name', models.CharField(blank=True, max_length=191, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('area_code', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_user', models.BooleanField(default=True)),
                ('approved', models.BooleanField(default=False, null=True)),
                ('is_available', models.BooleanField(blank=True, default=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_verified_mobile', models.BooleanField(default=False)),
                ('is_verified_email', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, max_length=199, null=True)),
                ('city', models.CharField(blank=True, max_length=191, null=True)),
                ('country', models.CharField(blank=True, max_length=191, null=True)),
                ('state', models.CharField(blank=True, max_length=191, null=True)),
                ('role', models.CharField(blank=True, choices=[('student', 'student'), ('teacher', 'teacher'), ('counsellor', 'counsellor')], max_length=191, null=True)),
                ('otp', models.PositiveIntegerField(blank=True, null=True)),
                ('otp_verify', models.BooleanField(default=False)),
                ('block_by_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.location')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
