# Generated by Django 3.2.5 on 2021-08-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210805_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_url',
            field=models.CharField(blank=True, max_length=199, null=True),
        ),
    ]
