# Generated by Django 3.2.5 on 2022-01-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
