# Generated by Django 3.2.5 on 2021-12-06 13:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notofication',
            new_name='Notification',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='notifications',
        ),
    ]
