# Generated by Django 3.2.5 on 2021-12-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportNumberEmail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country_code', models.CharField(default='+91', max_length=10)),
                ('number', models.IntegerField(default=0)),
                ('email', models.EmailField(default='vidyalu.help@mailinator.com', max_length=254)),
            ],
        ),
    ]
