# Generated by Django 3.2.5 on 2021-12-14 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vidyalu_admin', '0002_querymessagemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportnumberemail',
            name='country_code',
        ),
    ]
