# Generated by Django 3.2.5 on 2021-12-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidyalu_admin', '0003_remove_supportnumberemail_country_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSesssionCategoryModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_type', models.CharField(choices=[('course', 'course'), ('session', 'session')], max_length=100)),
                ('category', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
