# Generated by Django 3.2.5 on 2021-12-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidyalu_admin', '0004_coursesesssioncategorymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetterEmailModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'newsletteremail',
            },
        ),
    ]
