# Generated by Django 3.2.5 on 2021-12-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidyalu_admin', '0005_newsletteremailmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyAreasModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('competency_area', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
