# Generated by Django 3.2.5 on 2021-08-03 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.BooleanField(default=False)),
                ('qualification', models.CharField(blank=True, max_length=191, null=True)),
                ('certification', models.CharField(blank=True, max_length=191, null=True)),
                ('intrest', models.BooleanField(default=False)),
                ('stu_type', models.CharField(blank=True, choices=[('guest', 'guest'), ('member', 'member')], max_length=199, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Students',
                'verbose_name_plural': 'Student',
                'db_table': 'students',
            },
        ),
    ]
