# Generated by Django 3.2.5 on 2021-09-17 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_course_publish'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=191, null=True, unique=True)),
                ('card_number', models.CharField(blank=True, max_length=191, null=True, unique=True)),
                ('cvv_number', models.PositiveIntegerField(blank=True, null=True)),
                ('expiry_date', models.CharField(blank=True, max_length=191, null=True)),
                ('name_on_card', models.CharField(blank=True, max_length=191, null=True)),
                ('is_booking', models.BooleanField(default=False)),
                ('purchase_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_obj', to='teacher.course')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course_booking',
                'verbose_name_plural': 'Course_booking',
                'db_table': 'course_booking',
            },
        ),
    ]
