# Generated by Django 3.2.5 on 2021-09-27 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counsellor', '0009_session_publish'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0003_student_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=191, null=True, unique=True)),
                ('card_number', models.CharField(blank=True, max_length=191, null=True, unique=True)),
                ('cvv_number', models.PositiveIntegerField(blank=True, null=True)),
                ('expiry_date', models.CharField(blank=True, max_length=191, null=True)),
                ('name_on_card', models.CharField(blank=True, max_length=191, null=True)),
                ('is_booking', models.BooleanField(default=False)),
                ('purchase_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counsellor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counsellor_user', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_obj', to='counsellor.session')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_session_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session_booking',
                'verbose_name_plural': 'Session_booking',
                'db_table': 'session_booking',
            },
        ),
    ]
