# Generated by Django 3.2.5 on 2021-09-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_sessionbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursebooking',
            name='card_number',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='coursebooking',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='sessionbooking',
            name='card_number',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='sessionbooking',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
