# Generated by Django 3.2.5 on 2021-11-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_studenttest_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttest',
            name='test_attempt',
            field=models.BooleanField(default=False),
        ),
    ]
