# Generated by Django 3.2.5 on 2021-11-18 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0017_test_active'),
        ('student', '0008_studenttest_test_attempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_mark', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
                ('no_of_skip', models.IntegerField(blank=True, default=0, null=True)),
                ('no_of_attempt', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.test')),
            ],
            options={
                'db_table': 'test_result',
            },
        ),
    ]
