# Generated by Django 3.2.5 on 2021-11-30 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('counsellor', '0012_counsellorquestion'),
        ('student', '0009_testresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSessionTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.JSONField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('test_attempt', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counsellor.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counsellor.counsellortest')),
            ],
            options={
                'db_table': 'student_session_test',
            },
        ),
        migrations.CreateModel(
            name='SessionTestResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_mark', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
                ('no_of_skip', models.IntegerField(blank=True, default=0, null=True)),
                ('no_of_attempt', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counsellor.counsellortest')),
            ],
            options={
                'db_table': 'student_sessiontest_result',
            },
        ),
    ]
