# Generated by Django 3.2.5 on 2021-12-16 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counsellor', '0012_counsellorquestion'),
        ('teacher', '0017_test_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0010_sessiontestresult_studentsessiontest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionRating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('review', models.CharField(blank=True, max_length=5000, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counsellor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counsellor_rating_user', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='counsellor.session')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_sessionrateing_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session_rating',
                'verbose_name_plural': 'Session_rating',
                'db_table': 'session_rating',
            },
        ),
        migrations.CreateModel(
            name='CourseRating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('review', models.CharField(blank=True, max_length=5000, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.course')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_rating_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_courserateing_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course_rating',
                'verbose_name_plural': 'Course_rating',
                'db_table': 'course_rating',
            },
        ),
    ]
