# Generated by Django 3.2.5 on 2021-12-24 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0018_course_teacher_category'),
        ('counsellor', '0013_session_counsellor_category'),
        ('student', '0011_courserating_sessionrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('report', models.CharField(blank=True, max_length=5000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counsellor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counsellor_report_user', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='counsellor.session')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_sessionreport_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session_report',
                'verbose_name_plural': 'Session_report',
                'db_table': 'session_report',
            },
        ),
        migrations.CreateModel(
            name='CourseReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('report', models.CharField(blank=True, max_length=5000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.course')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_report_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_coursereport_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course_report',
                'verbose_name_plural': 'Course_report',
                'db_table': 'course_report',
            },
        ),
    ]
