# Generated by Django 3.2.5 on 2021-12-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_coursereport_sessionreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebooking',
            name='ammount_paid',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='ammount_paid',
            field=models.FloatField(default=0),
        ),
    ]
