# Generated by Django 3.2.5 on 2022-01-10 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20211229_0702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursebooking',
            old_name='ammount_paid',
            new_name='amount_paid',
        ),
        migrations.RenameField(
            model_name='sessionbooking',
            old_name='ammount_paid',
            new_name='amount_paid',
        ),
    ]
