# Generated by Django 3.2.5 on 2021-08-03 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Counsellor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(blank=True, max_length=191, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('certification', models.CharField(blank=True, max_length=191, null=True)),
                ('awards', models.CharField(blank=True, max_length=191, null=True)),
                ('id_proof_image', models.FileField(blank=True, null=True, upload_to='image/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counsellor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Counsellors',
                'verbose_name_plural': 'Counsellor',
                'db_table': 'counsellors',
            },
        ),
    ]
