# Generated by Django 3.2.5 on 2021-08-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counsellor',
            old_name='detail',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='counsellor',
            old_name='certification',
            new_name='services',
        ),
        migrations.RemoveField(
            model_name='counsellor',
            name='id_proof_image',
        ),
        migrations.AddField(
            model_name='counsellor',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='counsellor',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='counsellor',
            name='is_adharcard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='counsellor',
            name='is_pancard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='counsellor',
            name='is_passport',
            field=models.BooleanField(default=False),
        ),
    ]
