# Generated by Django 3.2.5 on 2021-08-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellor', '0003_counsellor_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellor',
            name='step',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
