# Generated by Django 3.2.5 on 2021-08-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellor', '0005_counsellor_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellor',
            name='awards',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='counsellor',
            name='services',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
