# Generated by Django 3.2.5 on 2021-09-03 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('counsellor', '0006_auto_20210823_0620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='SESSION TITLE', max_length=199)),
                ('year_of_experience', models.FloatField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=150, null=True)),
                ('contents', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('total_days', models.IntegerField(blank=True, null=True)),
                ('total_hours', models.IntegerField(blank=True, null=True)),
                ('weekly_schedule', models.CharField(blank=True, max_length=150, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='video/')),
                ('salient', models.TextField(blank=True, null=True)),
                ('block_by_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'session',
            },
        ),
    ]
