# Generated by Django 3.2.5 on 2021-09-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellor', '0008_auto_20210903_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
