# Generated by Django 3.2.5 on 2021-09-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellor', '0009_session_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
