# Generated by Django 3.2.5 on 2021-11-26 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('counsellor', '0011_counsellortest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounsellorQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(blank=True, max_length=1000, null=True)),
                ('option', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counsellor.session')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counsellor.counsellortest')),
            ],
            options={
                'db_table': 'counsellor_questions',
            },
        ),
    ]
