# Generated by Django 3.2.5 on 2021-12-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellor', '0012_counsellorquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='counsellor_category',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
