from student.models.students import Student
from student.models.course_booking import *
from student.models.session_booking import *
from student.models.student_test_model import *
from student.models.student_test_result import *
from student.models.student_session_test import StudentSessionTest
from student.models.student_sessiontest_result import SessionTestResult
from student.models.course_rating import *
from student.models.session_rating import *
from student.models.student_course_report import CourseReport
from student.models.student_session_report import SessionReport